### ISSUE TITLE
Add effects for Protection, Smite, and Boost/Lower Trait without dialog

### ISSUE THREAD

**Issue by basic-element** [SalieriC/SUCC#13]
Provide functions to add effects for Protection, Smite and Boost/Lower trait programmatically instead of creating a dialog box. This is for macros and modules that want to use SUCC to add the effects but automatically without UI intervention.

**Comment by SalieriC** [comment]
That's a very viable request and when I think about it, I would like to use that as well. I'll look into it. =)

**Comment by SalieriC** [comment]
Currently the script is listening to the `createActiveEffect` hook to start the function which renders the dialogue. I have no idea atm on how to prevent the dialogue from being rendered when the condition is applied. I could expose the function which edits the active effect with a variable to prevent the dialogue from being rendered but then there would be no active effect to update.
Maybe we need to make our own hooks or something. Another way would be to disable the effect updated completely but that would result in a great loss of functionality. I need more time to think about this so I'll mark this as blocked (by my own incompetence :D ) for now. Ideas on how to implement this are always welcome though.

**Comment by SalieriC** [comment]
By giving the created AE a flag the problem could be solved I think. We would need an exposed function in the API that functions as kind of a hub for creating various AEs giving them flags that store data preventing the dialogue from being rendered but still going through the builder functions. Incidentally, we already have two such functions; `succ.apply_status()` and `succ.toggle_status()`. So we could just give it an optional variable that - if provided - sets the flag.
The thing is: I'm not too familiar with the inner workings of these so I'm going to ask you, @javierriveracastro. Do you think it's possible to give the AE created in these two functions (or one of them) a flag in addition to the rest?

**Comment by SalieriC** [comment]
Turns out it is. And rather easy at that. Thus I'm now able to tackle this one. I'm envisioning big things already. But one thing at a time. I'll need to set up a groundwork for it. The thing is that we would need to include everything the user wants in the flags so that the builder can access it. I don't know how exactly that will look like but I'm thinking of something universal we could use for other purposes in the future. Like `data` that could hold any information.

**Comment by SalieriC** [comment]
This is done in git now. We'll not release it too soon in order to test it a little bit to uncover any potential bugs. 
For now, you can read about the API changes here: https://github.com/SalieriC/SUCC/blob/effect_builder_overhaul/documentation/succ-api.md#additional-data

If you have suggestions on what is a bit whacky or what could be done differently to suit your needs better, please let us know. =)
