### ISSUE TITLE
Conviction Suggestion

### ISSUE THREAD

**Issue by grendel111111** [SalieriC/SUCC#32]
Is it possible to get the AE for conviction to include expires at the start of the turn with warning flag, for those not using SWIM?

**Comment by SalieriC** [comment]
And you come around with that the instance I'm wrapping up the SWIM release, too late to include that? 🤣 
Sure, can be done, if the only thing you want is adding the end of turn message to end or refresh it. Everything else is out of scope for SUCC I think.

**Comment by grendel111111** [comment]
Yes just the to end or not to end question.

**Comment by SalieriC** [comment]
I thought about it. I don't really think there is a viable solution to set this up in SUCC atm. Reason being that the system does not provide an expiration setting for the start of a round; only start/end of turn is available and that's not in line with the rules. So without recreating code from SWIM there really is no way to implement that in SUCC and I think thus it is out of scope for this module. As much as I would like to have it otherwise. If the system ever introduces an expiration method for the start of round, this can easily be done.
Closing this for now, but feel free to comment if you want to argue with this decision.

**Comment by SalieriC** [comment]
That said, in the next version you will be able to configure this for yourself easily if you wish.
