### ISSUE TITLE
Feature Request: Add trait name to boost trait AE.

### ISSUE THREAD

**Issue by JasonSK22** [SalieriC/SUCC#44]
Adding the name of the trait being boosted into the AE label would be a nice to have.

So the AE would show something like "Boost Trait: Agility" as the Effect label.  

This would also be good to add to Smite, something like "Smite: Longsword".

I'd also like to say thank you for this Module, it is great!

**Comment by ddbrown30** [comment]
Yeah, I should be able to add something like that.

**Comment by SalieriC** [comment]
Thank you for your request.
This is currently not how it works because only one Boost/Lower, Smite and Protection instance is possible at any time using the GUI. This is intended more as a quick game aid rather than anything. Using the API however, multiple instances of the same effect can be added and labelled individually. SWIM for example provides an easy way to do this (although not yet v11 ready).
This however does not mean it shouldn't be changed. But it's something we should discuss first.

**Comment by JasonSK22** [comment]
Hi,

I see your point SalieriC, I missed the single application of the AE based on the Status Effect toggle.

**Comment by SalieriC** [comment]
Got to make a decision then. I have no particular strong feelings on either solution. Having the condition labelled is more clear but I fear it could mislead users to believe they can apply multiple from the GUI.

**Comment by ddbrown30** [comment]
I'm fine with including the trait in the name. I don't expect many people will think that they can add it multiple times but they will figure it out the first time they try.

That said, the system does actually support adding the condition multiple times, just not by using the status marker on the token. Calling addCondition through the API with allowDuplicates true will apply them. In fact, SWIM already supports this using the Effect Builder macro.

**Comment by SalieriC** [comment]
Gone in git.
