### ISSUE TITLE
Icon Not Appearing When Selecting "Bound" Condition

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SUCC#59]
**Issue Description**:
When I select the "Bound" condition, the associated icon is not appearing as expected. 

Error
![image](https://github.com/SalieriC/SUCC/assets/4999783/afd15e79-0743-45db-8a0a-33cfbb30adcf)

https://github.com/SalieriC/SUCC/assets/4999783/158c81d8-d33f-4d7a-a642-50503e664730

**Comment by ddbrown30** [comment]
What is the filename it's looking for?

You reported a similar bug awhile ago that was fixed by restoring defaults. I'm guessing that will fix it again now but I would be curious to know what you're doing that keeps putting you into a bad state. There's probably a bug somewhere (unless it's just that you keep accidentally changing the image paths or something), so I'd like to fix that.

**Comment by brunocalado** [comment]
> What is the filename it's looking for?
> 
> You reported a similar bug awhile ago that was fixed by restoring defaults. I'm guessing that will fix it again now but I would be curious to know what you're doing that keeps putting you into a bad state. There's probably a bug somewhere (unless it's just that you keep accidentally changing the image paths or something), so I'd like to fix that.

oh boy... Restore default fixed. Thank you.
