### ISSUE TITLE
How to specify "swade.expiration" when I call addCondition()?

### ISSUE THREAD

**Issue by r2roberts** [SalieriC/SUCC#66]
I saw that you added duration to game.succ.addCondition(). I'm very glad, but how do I specify 
```
data.flags = {
    "swade.expiration":
      CONFIG.SWADE.CONST.STATUS_EFFECT_EXPIRATION.EndOfTurnPrompt,
  };
```
while calling addCondition()?

**Comment by SalieriC** [comment]
I know reading changelogs isn't trendy but maybe it helps in this case. :D
https://github.com/SalieriC/SUCC/blob/main/CHANGELOG.md#230---2024-01-20-aka-enduring-effects

Let me know if not.

**Comment by r2roberts** [comment]
I saw that changelog entry, but it doesn't tell me how to change swade.expiration, per se. Here's what I want to do...
```
async function main() {
  const cond = game.succ.conditions.find((e) =>
    e.name.toLowerCase().includes("invisible"),
  );
  await game.succ.addCondition(cond.id, null, {
    duration: 5,
    effectOptions: {
      swade: {
        expiration: CONFIG.SWADE.CONST.STATUS_EFFECT_EXPIRATION.EndOfTurnPrompt,
      },
    },
  });
}
```
But that, obviously, doesn't work.

**Comment by SalieriC** [comment]
Oh, now I get what you mean. Note that expiration and duration is not the same. The API now allows for passing duration but I'm not sure it is capable of changing the expiration, @ddbrown30 could possibly answer that. But I think in order to achieve anything you'd have to pass the expiration as flags anyway since SWADE does this with flags. So this maybe:
```js
await game.succ.addCondition(cond.id, null, {
    effectOptions: {
        flags: {
            swade: {
                expiration: /*whatever it actually is*/,
            },
        }
    },
});
```
But again, not sure the api handles that.

**Comment by r2roberts** [comment]
Nope, that didn't work.
I also tried...
```
await game.succ.addCondition(cond.id, null, {
    duration: 5,
    effectOptions: {
      flags: {
        "swade.expiration": CONFIG.SWADE.CONST.STATUS_EFFECT_EXPIRATION.EndOfTurnPrompt,
      },
    },
  });
```

**Comment by r2roberts** [comment]
I found a work around... I went into the SUCC Condition Lab, and changed the definition of EFFECT.StatusInvisible's Active Effect to include End of Turn Prompt in its Turn Behavior.

**Comment by r2roberts** [comment]
I still think this should be part of your API, so it can be overwritten on a case by case basis, using a macro.

**Comment by ddbrown30** [comment]
Yeah, changing it in the condition lab is what I would have suggested.

As for adding it to the API, I don't see much value in that. There's no reason you have to use SUCC to add an effect to an actor. If you want full control over all the params, just add the effect yourself.

Do you have an example of where you would want to be able to change the expiration behaviour on an effect only in a specific situation rather than just updating the entry in the lab?

**Comment by r2roberts** [comment]
I cannot come up with an example off hand. I usually want all of my temporary effects to be EndOfTurnPrompt.
By your meaning "want full control" do you mean for me to use the token.document.toggleActiveEffect() interface? That's how I originally wrote my macro.
```
async function old() {
  const data = foundry.utils.deepClone(
    CONFIG.statusEffects.find((e) => e.id === "invisible"),
  );
  data.duration = { rounds: 5 };
  data.flags = {
    "swade.expiration":
      CONFIG.SWADE.CONST.STATUS_EFFECT_EXPIRATION.EndOfTurnPrompt,
  };
  await token.document.toggleActiveEffect(data);
}
```

**Comment by ddbrown30** [comment]
If you just want all of your effects to be EndOfTurnPrompt, then I would definitely suggest just updating them in the lab.

And yeah, that's what I meant. Using the default Foundry API to create the effect. That's basically all that SUCC is doing.

**Comment by r2roberts** [comment]
Thanks

**Comment by SalieriC** [comment]
Can we close this issue now or is there anything left unclear? BTW: You can close issues yourself when you think they are resolved @r2roberts.

**Comment by r2roberts** [comment]
Yes, go ahead and close it.
