### ISSUE TITLE
Request for Confidential Actor Sheet Conditions

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SUCC#76]
I would like conditions I change on the actor sheet to be hidden from players. Currently, it appears in the chat that you performed this action and for which actor.

**Comment by SalieriC** [comment]
You can turn off chat messages in the settings where all the other settings for modules are. just uncheck the option for chat messages and you're good to go.

**Comment by brunocalado** [comment]
> You can turn off chat messages in the settings where all the other settings for modules are. just uncheck the option for chat messages and you're good to go.

I don't want the messages to go away. I want the players to not see them. They should show only for the GM.

**Comment by ddbrown30** [comment]
There's not really a way to do that but I'm open to suggestions. It's all driven off the AE being created and destroyed so we have no context for if the change came from editing the actor directly or by setting a condition on the token.

We could maybe add an option that makes it so that users can only see the chat card for actors they own but that would mean that you wouldn't see other PCs. I think that's as close as we could get.

**Comment by brunocalado** [comment]
> There's not really a way to do that but I'm open to suggestions. It's all driven off the AE being created and destroyed so we have no context for if the change came from editing the actor directly or by setting a condition on the token.
> 
> We could maybe add an option that makes it so that users can only see the chat card for actors they own but that would mean that you wouldn't see cards for other PCs. I think that's as close as we could get.

The chat card could just respect the roll mode:
![image](https://github.com/SalieriC/SUCC/assets/4999783/e1277afe-ff9a-4516-9ec5-f98e962fb688)

**Comment by brunocalado** [comment]
So, if I set the Private only I can see the cards.
