### ISSUE TITLE
Broken Defeated Icon

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SUCC#80]
The defeated icon is broken.

![image](https://github.com/SalieriC/SUCC/assets/4999783/d7d431ef-e8de-4828-9727-818288b24b2f)

**Comment by brunocalado** [comment]
![image](https://github.com/SalieriC/SUCC/assets/4999783/59865007-008d-49a8-a4ad-83ca9ac957e9)

**Comment by SalieriC** [comment]
Thank you for your time.
Please note that the conditions ID changed to "dead" in the system and so has the icons name in SUCC. SUCC should've been able to get the correct icon however. 🤔

**Comment by ddbrown30** [comment]
Due to changes in the system level, we had to make changes in SUCC. The defeated condition doesn't exist at all anymore and you'll need to restore defaults to fix it. I didn't realize this was going to be a problem when I made this change otherwise I would have added some migration logic to handle this all automatically. I also got burned by this in my game last night.

**Comment by brunocalado** [comment]
Reset, delete and reload solved. Tks all
